# Generated by Django 4.1.5 on 2023-02-14 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordpair', '0002_alter_word_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='first_word',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='second_word',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
